name: Node.js CI

on:
  push:
    branches: ["main", "fix/workflow-changes"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    name: Backend test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./quirknotes/backend

    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: ["4.2", "4.4", "5.0", "6.0"]

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm i

      - name: Start server
        run: npm run dev

      - name: Run tests
        run: npm test
